Add required priv-app permissions for SystemUIGoogle
fixes:
java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.systemui (/system_ext/priv-app/SystemUIGoogle): android.permission.ACCESS_CONTEXT_HUB, com.android.systemui (/system_ext/priv-app/SystemUIGoogle): android.permission.REGISTER_STATS_PULL_ATOM, com.android.systemui (/system_ext/priv-app/SystemUIGoogle): android.permission.SET_WALLPAPER_COMPONENT}